#if !defined(ISR80H_H)
#define ISR80H_H

enum SystemCommands {
    // SYSTEM_COMMAND_0_SUM,
    SYSTEM_COMMAND_0_EXIT,
    SYSTEM_COMMAND_1_PRINT,
    SYSTEM_COMMAND_2_PUTCHAR,
    SYSTEM_COMMAND_3_GETKEY,
    SYSTEM_COMMAND_4_MALLOC,
    SYSTEM_COMMAND_5_FREE,
    SYSTEM_COMMAND_6_PROCESS_LOAD_START,
    SYSTEM_COMMAND_7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND_8_GET_PROGRAM_ARGUMENTS,
};

void isr80h_register_all_commands();

#endif // ISR80H_H
